CREATE TABLE "ATOS"."TAREAS" (
		"ID_TAREA" NUMBER(5, 0) NOT NULL,
		"NOMBRE_TAREA" VARCHAR2(100) NOT NULL,
		"DESCRIPCION_TAREA" VARCHAR2(2000),
		"ESTADO" VARCHAR2(50)
	);
ALTER TABLE "ATOS"."TAREAS" ADD CONSTRAINT "ID_TAREA_PK" PRIMARY KEY ("ID_TAREA");

CREATE TABLE "ATOS"."USUARIOS" (
		"ID_USUARIO" NUMBER(5, 0) NOT NULL,
		"DAS" VARCHAR2(15) NOT NULL,
		"NOMBRE" VARCHAR2(20) NOT NULL,
		"APELLIDO" VARCHAR2(20) NOT NULL,
		"PASSWORD" VARCHAR2(10) NOT NULL,
		"CODIGO_ROL" NUMBER(2 , 0)
	);
ALTER TABLE "ATOS"."USUARIOS" ADD CONSTRAINT "ID_USUARIO_PK" PRIMARY KEY ("ID_USUARIO");

CREATE TABLE "ATOS"."ROLES" (
		"CODIGO_ROL" NUMBER(2 , 0) NOT NULL,
		"DESCRIPCION_ROL" VARCHAR2(100)
	);
ALTER TABLE "ATOS"."ROLES" ADD CONSTRAINT "CODIGO_ROL_PK" PRIMARY KEY ("CODIGO_ROL");

CREATE TABLE "ATOS"."ROLES_TAREAS" (
		"CODIGO_ROL" NUMBER(2 , 0) NOT NULL,
		"CODIGO_TAREA" NUMBER(2 , 0) NOT NULL
	);
ALTER TABLE "ATOS"."ROLES_TAREAS" ADD CONSTRAINT "ROLES_TAREAS_PK" PRIMARY KEY ("CODIGO_ROL", "CODIGO_TAREA");


ALTER TABLE "ATOS"."ROLES_TAREAS" ADD CONSTRAINT "CODIGO_TAREA_FK" FOREIGN KEY ("CODIGO_TAREA")
	REFERENCES "ATOS"."TAREAS" ("ID_TAREA")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "ATOS"."USUARIOS" ADD CONSTRAINT "CODIGO_ROL_USUARIOS_FK" FOREIGN KEY ("CODIGO_ROL")
	REFERENCES "ATOS"."ROLES" ("CODIGO_ROL")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "ATOS"."ROLES_TAREAS" ADD CONSTRAINT "CODIGO_ROL_FK" FOREIGN KEY ("CODIGO_ROL")
	REFERENCES "ATOS"."ROLES" ("CODIGO_ROL")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
	
	CREATE UNIQUE INDEX "ATOS"."ID_TAREA_PK" ON "ATOS"."TAREAS" ("ID_TAREA" ASC);

CREATE UNIQUE INDEX "ATOS"."ID_USUARIO_PK" ON "ATOS"."USUARIOS" ("ID_USUARIO" ASC);

CREATE UNIQUE INDEX "ATOS"."ROLES_TAREAS_PK" ON "ATOS"."ROLES_TAREAS" ("CODIGO_ROL" ASC, "CODIGO_TAREA" ASC);

CREATE UNIQUE INDEX "ATOS"."CODIGO_ROL_PK" ON "ATOS"."ROLES" ("CODIGO_ROL" ASC);